export const ERROR_MESSAGES = {
  required: 'Trường này là bắt buộc',
  invalidEmail: 'Email không hợp lệ',
  invalidDate: 'Ngày sinh không hợp lệ',
  passwordTooShort: 'Mật khẩu phải có ít nhất 8 ký tự',
  passwordTooLong: 'Mật khẩu không được quá 16 ký tự',
  passwordNoLowercase: 'Mật khẩu phải có ít nhất một chữ cái thường',
  passwordNoUppercase: 'Mật khẩu phải có ít nhất một chữ cái hoa',
  passwordNoSpecialChar: 'Mật khẩu phải có ít nhất một ký tự đặc biệt',
  passwordNotMath: 'Mật khẩu xác nhận không khớp',
  dateInFuture: 'Ngày sinh không được lớn hơn ngày hiện tại',
  lastNameTooLong: 'Họ không được quá 50 ký tự',
  lastNameTooShort: 'Họ phải có ít nhất một ký tự',
  firstNameTooLong: 'Tên không được quá 50 ký tự',
  firtNameTooShort: 'Tên phải có ít nhất một ký tự',
}
