export const ReviewErrorMessages = {
  CREATE_REVIEW_ERROR: 'Failed to create review',
  UPDATE_REVIEW_ERROR: 'Failed to update review',
  DELETE_REVIEW_ERROR: 'Failed to delete review',
  FETCH_REVIEWS_ERROR: 'Failed to fetch reviews',
  FETCH_REVIEW_ERROR: 'Failed to fetch review',
  REVIEW_NOT_FOUND: 'Review not found',
  INVALID_REVIEW_ID: 'Invalid review ID',
  INVALID_REVIEW_DATA: 'Invalid review data',
  ORDER_NOT_COMPLETED: 'Cannot review products from uncompleted orders',
  PRODUCT_NOT_PURCHASED: 'You have not purchased this product',
  REVIEW_ALREADY_EXISTS: 'You have already reviewed this product for this order',
  REVIEW_EDIT_EXPIRED: 'Cannot edit review after 7 days',
  REVIEW_ALREADY_EDITED: 'Review can only be edited once',
  UPLOAD_IMAGE_ERROR: 'Failed to upload review image',
  INVALID_IMAGE_FORMAT: 'Invalid image format. Only JPG, PNG and GIF are allowed',
  IMAGE_SIZE_TOO_LARGE: 'Image size must be less than 5MB',
  TOO_MANY_IMAGES: 'Maximum 5 images allowed per review',
};
