version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_ecommerce
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_ecommerce
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local
