version: '3.8'

services:
  app:
    build: .
    container_name: app_ecommerce
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
